name: marp-to-pages
concurrency: marp-to-pages
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy images
        run: mkdir build && cp -R img build/img

      - name: Marp Build (README)
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: README.md -o build/index.html
        env:
          MARP_USER: root:root

      - name: Marp Build (README.pdf)
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: README.md -o build/README.pdf
        env:
          MARP_USER: root:root

      - name: Marp Build (README.pptx)
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: README.md -o build/README.pptx
        env:
          MARP_USER: root:root

      - name: Marp Build (docs folder)
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: -I docs/ -o build/docs/
        env:
          MARP_USER: root:root

      - name: Deploy Github Pages
        if: ${{ github.event_name == 'push' }}
        uses: rayluo/github-pages-overwriter@v1.2
        with:
          source-directory: ./build/
